Repository ProvLabs/vault, pull requests merged in 2025-09, with the labels that each got.

#47 Phase 2 - Integrate Valuation Engine and Multi-Asset Swaps
  keeper/msg_server.go
  keeper/msg_server_security_test.go
  keeper/msg_server_test.go
  keeper/query_server.go
  keeper/query_server_test.go
  keeper/reconcile.go
  keeper/suite_test.go
  keeper/valuation_engine.go
  keeper/valuation_engine_test.go
  keeper/vault.go
  keeper/vault_test.go
  types/msgs.go
  types/msgs_test.go
  types/vault.go
  types/vault_test.go
Labels: enhancement, mvp 1

#51 Expedite Pending Queue Entries
  api/v1/events.pulsar.go
  api/v1/genesis.pulsar.go
  api/v1/query.pulsar.go
  api/v1/query_grpc.pb.go
  api/v1/tx.pulsar.go
  api/v1/tx_grpc.pb.go
  api/v1/vault.pulsar.go
  keeper/genesis.go
  keeper/genesis_test.go
  keeper/keeper.go
  keeper/msg_server.go
  keeper/msg_server_test.go
  keeper/query_server.go
  keeper/query_server_test.go
  keeper/queue_test.go
  keeper/valuation_engine.go
  module.go
  proto/vault/v1/events.proto
  proto/vault/v1/genesis.proto
  proto/vault/v1/query.proto
  proto/vault/v1/tx.proto
  proto/vault/v1/vault.proto
  queue/payout_timeout.go
  queue/pending_swap_out.go
  queue/pending_swap_out_test.go
  queue/pending_withdrawal.go
  queue/pending_withdrawal_test.go
  types/events.go
  types/events.pb.go
  types/genesis.pb.go
  types/keys.go
  types/msgs.go
  types/msgs_test.go
  types/query.pb.go
  types/query.pb.gw.go
  types/tx.pb.go
  types/vault.pb.go
Labels: mvp 1

#50 Asynchronous Withdrawals with Time-Locked Queue
  api/v1/events.pulsar.go
  api/v1/tx.pulsar.go
  api/v1/vault.pulsar.go
  keeper/abci.go
  keeper/genesis_test.go
  keeper/msg_server.go
  keeper/msg_server_security_test.go
  keeper/msg_server_test.go
  keeper/payout.go
  keeper/payout_test.go
  keeper/query_server.go
  keeper/query_server_test.go
  keeper/vault.go
  keeper/vault_test.go
  proto/vault/v1/events.proto
  proto/vault/v1/tx.proto
  proto/vault/v1/vault.proto
  queue/pending_swap_out.go
  queue/pending_swap_out_test.go
  simulation/operations_test.go
  types/events.go
  types/events.pb.go
  types/expected_keepers.go
  types/tx.pb.go
  types/vault.go
  types/vault.pb.go
Labels: mvp 1

#62 Allow toggling of swap in/out when vault paused
  keeper/msg_server.go
  keeper/msg_server_test.go
Labels: mvp 1

#60 Fix dequeue failures that can cause zombie entries
  keeper/export_test.go
  keeper/payout.go
  keeper/payout_test.go
  keeper/reconcile.go
  types/payout.go
Labels: mvp 1

#65 Add bypass to deposit interest funds
  keeper/msg_server.go
  keeper/msg_server_test.go
Labels: bug, mvp 1

#56 Improve share calculation precision and add multi-asset query support
  api/v1/query.pulsar.go
  keeper/query_server.go
  keeper/query_server_test.go
  keeper/valuation_engine.go
  keeper/valuation_engine_test.go
  module.go
  proto/vault/v1/query.proto
  types/query.pb.go
  utils/shares.go
  utils/shares_test.go
Labels: mvp 1

#66 Vault auto pause event update
  api/v1/events.pulsar.go
  keeper/vault.go
  keeper/vault_test.go
  proto/vault/v1/events.proto
  types/events.go
  types/events.pb.go
  types/params.go
  types/params.pb.go
Labels: enhancement, mvp 1

#24 Add Vault Module Specs
  README.md
  spec/01_concepts.md
  spec/02_state.md
  spec/03_messages.md
  spec/04_events.md
  spec/05_queries.md
  spec/06_blocker.md
Labels: documentation, mvp 1
