Repository ProvLabs/vault, pull requests merged in 2025-10, with the labels that each got.

#72 Fix vault account validation check in genesis
  keeper/genesis.go
Labels: bug

#78 Update to use custom attribute constructor.
  simulation/provenance.go
Labels: mvp 1

#79 Fix simulation test generation of restricted denom length
  simulation/rand.go
Labels: bug

#82 Fix event coin types to be strings of <amount><denom>
  api/v1/events.pulsar.go
  keeper/msg_server_test.go
  keeper/reconcile_test.go
  keeper/suite_test.go
  proto/vault/v1/events.proto
  types/events.go
  types/events.pb.go
Labels: enhancement, mvp 1

#87 Fix paused NAV-per-share to divide PausedBalance by total shares
  keeper/valuation_engine.go
  keeper/valuation_engine_test.go
Labels: bug, mvp 1

#86 Add suggestion to split up vault checks.
  keeper/state.go
Labels: enhancement, mvp 1

#88 Fix overflow risk in NAV volume handling within UnitPriceFraction
  keeper/valuation_engine.go
Labels: bug, mvp 1

#85 Add missing validation to `MsgCreateVaultRequest` and `MsgSwapOutRequest`
  types/msgs.go
  types/msgs_test.go
  types/vault.go
Labels: enhancement, mvp 1
